steps:
  # Install dependencies
  - name: 'python:3.12-slim'
    id: 'install'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install uv
        uv sync --frozen

  # Run linting
  - name: 'python:3.12-slim'
    id: 'lint'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install uv
        uv run ruff check src/
        uv run ruff format --check src/

  # Run type checking
  - name: 'python:3.12-slim'
    id: 'typecheck'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install uv
        uv run ty check src/

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
      - '.'

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}'

  # Deploy to Cloud Run Jobs
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy'
    args:
      - 'run'
      - 'jobs'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--project=${PROJECT_ID}'
      - '--set-secrets=DATABASE_URL=DATABASE_URL:latest,SLACK_WEBHOOK_URL=SLACK_WEBHOOK_URL:latest,GOOGLE_WORKSPACE_CREDENTIALS=GOOGLE_WORKSPACE_CREDENTIALS:latest'
      - '--max-retries=3'
      - '--task-timeout=30m'
      - '--memory=512Mi'
      - '--cpu=1'

substitutions:
  _SERVICE_NAME: coupon-mention-tracker
  _REGION: europe-west3
  _REPOSITORY: containers

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
